# Generated by Django 3.2 on 2021-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
