# Generated by Django 3.2 on 2021-05-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20210430_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedtickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
