# Generated by Django 3.2 on 2021-05-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ticketorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
