# Generated by Django 3.2 on 2021-05-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ticketorder_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='tickets',
            field=models.TextField(default='[]'),
        ),
    ]
